itkg_php_redmon_instance_new:
    pattern:   /instance/new
    defaults:  { _controller: ItkgPhpRedmonBundle:Crud:new }

itkg_php_redmon_instance_create:
    pattern:   /instance/create
    defaults:  { _controller: ItkgPhpRedmonBundle:Crud:create }
    requirements:
        _method:  POST
        
itkg_php_redmon_instance_edit:
    pattern:   /instance/edit/{id}
    defaults:  { _controller: ItkgPhpRedmonBundle:Crud:edit }
    
itkg_php_redmon_instance_update:
    pattern:   /instance/update/{id}
    defaults:  { _controller: ItkgPhpRedmonBundle:Crud:update }
    requirements:
        _method:  POST
        
itkg_php_redmon_instance_delete:
    pattern:   /instance/delete/{id}
    defaults:  { _controller: ItkgPhpRedmonBundle:Crud:index }
    
itkg_php_redmon_instance_select:
    pattern:   /instance/select/{id}
    defaults:  { _controller: ItkgPhpRedmonBundle:Dash:select }

itkg_php_redmon_instance_client:
    pattern:   /clients
    defaults:  { _controller: ItkgPhpRedmonBundle:Dash:client }

itkg_php_redmon_instance_configuration:
    pattern:   /configuration
    defaults:  { _controller: ItkgPhpRedmonBundle:Dash:configuration }


itkg_php_redmon:
    pattern:   /
    defaults:  { _controller: ItkgPhpRedmonBundle:Dash:index }
    
itkg_php_redmon_admin_flushdb:
    pattern:   /admin/flush-db/{id}
    defaults:  { _controller: ItkgPhpRedmonBundle:Admin:flushDb }

itkg_php_redmon_admin_flushall:
    pattern:   /admin/flush-all
    defaults:  { _controller: ItkgPhpRedmonBundle:Admin:flushAll }